---SCHEMA DEFINITION

CREATE TABLE IF NOT EXISTS USERS_ (
ID                              INTEGER             PRIMARY KEY AUTO_INCREMENT,
USER_NAME                       VARCHAR(255)        NOT NULL,
USER_EMAIL                      VARCHAR(255)        NOT NULL,
USER_TOKEN                      VARCHAR(255)        NOT NULL
);


CREATE TABLE IF NOT EXISTS EVENTS_ (
ID                              INTEGER             PRIMARY KEY AUTO_INCREMENT,
EVENT_TITLE                     VARCHAR(255)        NOT NULL,
EVENT_DESCRIPTION               VARCHAR(2000)       NOT NULL,
EVENT_DATE                      TIMESTAMP           NOT NULL,
EVENT_END_DATE					TIMESTAMP			NULL DEFAULT NULL,
EVENT_LOCATION                  VARCHAR(255)        NOT NULL,
EVENT_OWNER                     INTEGER             NOT NULL, 
FOREIGN KEY (EVENT_OWNER) REFERENCES USERS_(ID),
UNIQUE (EVENT_TITLE, EVENT_OWNER)
);


CREATE TABLE IF NOT EXISTS EVENT_LIKES (
ID                              INTEGER             PRIMARY KEY AUTO_INCREMENT,
EVENT_ID                     	INTEGER  	       	NOT NULL,
USER_ID                      	INTEGER       		NOT NULL,
FOREIGN KEY (EVENT_ID) REFERENCES EVENTS_(ID),
FOREIGN KEY (USER_ID) REFERENCES USERS_(ID),
UNIQUE (EVENT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS EVENT_PARTICIPANTS (
ID                              INTEGER             PRIMARY KEY AUTO_INCREMENT,
EVENT_ID                     	INTEGER  	       	NOT NULL,
USER_ID                      	INTEGER       		NOT NULL,
FOREIGN KEY (EVENT_ID) REFERENCES EVENTS_(ID),
FOREIGN KEY (USER_ID) REFERENCES USERS_(ID),
UNIQUE (EVENT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS CATEGORIES_ (
ID								INTEGER				PRIMARY KEY AUTO_INCREMENT,
CATEGORY_TITLE					VARCHAR(100)		NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIES_LIKES (
ID 								INTEGER 			PRIMARY KEY AUTO_INCREMENT,
CATEGORY_ID						INTEGER 			NOT NULL,
USER_ID							INTEGER				NOT NULL,
FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES_(ID) ON DELETE CASCADE,
FOREIGN KEY(USER_ID) REFERENCES USERS_(ID) 			ON DELETE CASCADE,
UNIQUE(CATEGORY_ID, USER_ID)
);

ALTER TABLE EVENTS_
ADD CATEGORY_ID 				INTEGER 			NULL DEFAULT NULL,
ADD CONSTRAINT FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES_(ID) ON DELETE SET NULL;